config/routes.rb
StormOlive::Application.routes.draw do
  resources :sessions, :only => [:new, :create, :destroy]
  resources :users

  get "users/show"

  match '/about',   :to => 'pages#about'
  match '/blog',   :to => 'pages#blog'
  match '/signup',   :to => 'users#new'
  match '/signin',   :to => 'sessions#new'
  match '/signout',   :to => 'sessions#destroy'

  root :to => 'pages#home'

end

app/models/user.rb
# == Schema Information
#
# Table name: users
#
#  id                 :integer         not null, primary key
#  firstname          :string(255)
#  lastname           :string(255)
#  nick               :string(255)
#  email              :string(255)
#  created_at         :datetime
#  updated_at         :datetime
#  encrypted_password :string(255)
#  salt               :string(255)
#

class User < ActiveRecord::Base
    attr_accessor :password
    attr_accessible :firstname, :lastname, :nick, 
                    :email, :password, :password_confirmation
                    
                    

    email_regex = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i

    validates :firstname, :presence => true,
                          :length => { :maximum => 50 }

    validates :lastname, :presence => true,
                          :length => { :maximum => 50 }

    validates :nick, :presence => true,
                     :uniqueness => { :case_sensitive => false },
                          :length => { :maximum => 19 }

    validates :email, :presence => true,
                      :format => { :with => email_regex },
                      :uniqueness => { :case_sensitive => false }
    # Automatically create the virtual attribute 'password_confirmation'
    validates :password, :presence => true,
                         :confirmation => true,
                         :length => { :within => 6..40 }

    before_save :encrypt_password

    def has_password?(submitted_password)
      self.encrypted_password == encrypt(submitted_password)
    end
    
    def self.authenticate(email, password)
      user = find_by_email(email)
      (user && user.has_password?(password)) ? user : nil
    end

    def self.authenticate_with_salt(id, cookie_salt)
      user = find_by_id(id)
      (user && user.salt == cookie_salt) ? user : nil
    end
#remove this comment
    private
      def encrypt_password
        self.salt = make_salt if new_record?
        self.encrypted_password = encrypt(password)
      end

      def encrypt(string)
        secure_hash("#{salt}--#{string}")
      end

      def make_salt
        secure_hash("#{Time.now.utc}--#{password}")
      end

      def secure_hash(string)
        Digest::SHA2.hexdigest(string)
      end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
  include SessionsHelper
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
    @title = 'Home'
  end

  def about
    @title = 'About'
  end

  def blog
    @title = "Blog"
  end

end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
    @title = "Sign in"
  end

  def create
    user = User.authenticate(params[:session][:email],
                             params[:session][:password])
    if user.nil?
      flash.now[:error] = "Invalid email/password combination."
      @title = "Sign in"
      render 'new'
    else
      # Sign the user in and redirect to the user's show page.
      sign_in user
      redirect_to user
    end
  end

  def destroy
    sign_out
    redirect_to root_path
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def new
    @user = User.new
    @title = "Sign up"
  end
  
  def show
    @user = User.find(params[:id])
    @title = @user.nick
  end

  def create
    @user = User.new(params[:user])
    if @user.save
      flash[:success] = "Welcome!"
      sign_in @user
      redirect_to user_path(@user)
    else 
      @title = "Sign up"
      render 'new'
    end
  end

  def edit
    @user = User.find(params[:id])
    @title = "Muokkaa"
  end

  def destroy
    @user.destroy
    redirect_to users_path
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def title
    base_title = "Storm Olive, the greatest blog-site ever seen!"
    if @title.nil?
      base_title
    else
      "#{base_title} | #{@title}"
    end
  end
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
  def logger
    RAILS_DEFAULT_LOGGER
  end

  def sign_in(user)
    cookies.permanent.signed[:remember_token] = [user.id, user.salt]
    self.current_user = user
  end

  def current_user=(user)
    @current_user = user
  end
  
  def current_user
    @current_user ||= user_from_remember_token
  end

  def signed_in?
    # !current_user.nil? doesnt work TODO: why?
    !current_user.nil?
  end

  def sign_out
    cookies.delete(:remember_token)
    self.current_user = nil
  end

  private
    def user_from_remember_token
      User.authenticate_with_salt(*remember_token)
    end

    def remember_token
      cookies.signed[:remember_token] || [nil, nil]
    end
end

app/helpers/users_helper.rb
module UsersHelper
  def gravatar_for(user, options = { :size => 50})
    gravatar_image_tag(user.email.downcase, :alt => user.nick,
                                            :class => 'gravatar',
                                            :gravatar => options)
    end
end

app/views/layouts/_footer.html.erb
<footer>
  <p>Created by tojuhaka@gmail.com</p>
  <p>
    <%= debug(params) if Rails.env.development? %>
  </p>
</footer>

app/views/layouts/_header.html.erb
<header id="main_header"> 
    <ul>
        <li>
        <h1>Aivolävistys </h1>
        </li>
        <% if signed_in? %>
            <li><h1>TOIMII</h1></li>
        <% end %>
    </ul>
</header>

app/views/layouts/_intro.html.erb
<section id="intro">
 <header>  
        <h2>Do you love olives as much as we do?</h2>  
    </header>  
  <%= image_tag("intro_flower.png", :alt => "intro_olive", :class => "round") %>
</section>

app/views/layouts/_main.html.erb
<section>
<!-- TODO: position wrong? -->
    <section class="round">
      <% flash.each do |key, value| %>
        <div class="flash" <%= key %>"><%= value %> </div>
      <% end %>
<%= yield %>
</section>

app/views/layouts/_nav.html.erb
<nav>
  <ul>
    <li><%= link_to "Etusivu", root_path %></li>
    <li><%= link_to "Levyt", root_path %></li>
    <li><%= link_to "Keikat", blog_path %></li>
    <li><%= link_to "Galleria", blog_path %></li>
    <li><%= link_to "Bändi", about_path %></li>
  </ul>
</nav>

app/views/layouts/_sidebar.html.erb
<aside>
  <section>
    <header>
      <h3>Linkkejä</h3>
    </header>
    <ul>
      <li><%= link_to "Login", signin_path %></li>
      <li><%= link_to "Register", signup_path %></li>
      <li><a href="#">Adipisicing elit sed</a></li>
      <li><a href="#">Do eiusmod tempor</a></li>
      <li><a href="#">Incididunt ut labore</a></li>
    </ul>
  </section>
  <section>
    <header>

      <h3>Jäsenet</h3>
    </header>
    <ul>
      <li><a href="#">Jukkis</a></li>
      <li><a href="#">Matu (basisti)</a></li>
      <li><a href="#">Se joku laulaja</a></li>
      <li><a href="#">Joku rumpali (vissii matu)</a></li>

      <li><a href="#">April 2009</a></li>
    </ul>
  </section>
</aside>

app/views/layouts/_stylesheets.html.erb
<%= stylesheet_link_tag 'aivo', :media => 'screen' %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= title %></title>
    <%= csrf_meta_tag %>
    <%= render 'layouts/stylesheets' %>
  </head>
  <body>
    <%= render 'layouts/header' %>
    <%= render 'layouts/nav' %>
    <div id="content">
      <div id="mainContent">
        <%= render 'layouts/main' %>
      </div>
      <%= render 'layouts/sidebar' %>
    </div>
    <%= render 'layouts/footer' %>
  </body>
</html>

app/views/pages/about.html.erb
<p>About</p>

app/views/pages/blog.html.erb
    <article class="blogPost">  
        <header>  
        <h2>This is the title of a blog post</h2>  
        <p>Posted on <time datetime="2009-06-29T23:31:45+02:00">
            June 29th 2009</time> by <a href="#">Mads Kjaer</a> - 
            <a href="#comments">3 comments</a></p>  
        </header>  
        <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit.
            Proin euismod tellus eu orci imperdiet nec rutrum lacus 
            blandit. Cras enim nibh, sodales ultricies elementum vel, 
            fermentum id tellus. Proin metus odio, ultricies eu pharetra 
            dictum, laoreet id odio...</p>  
    </article>  

    <section id="comments">  
        <header>  
            <h3>Comments</h3>  
        </header>  
        <article>  
            <header>  
                <a href="#">George Washington</a> on 
                    <time datetime="2009-06-29T23:35:20+01:00">
                        June 29th 2009 at 23:35</time>  
            </header>  
            <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit, 
                sed do eiusmod tempor incididunt ut labore et dolore magna 
                aliqua. Ut enim ad minim veniam, quis nostrud exercitation 
                ullamco laboris nisi ut.</p>  
        </article>  
        <article>  
            <header>  
                <a href="#">Benjamin Franklin</a> on 
                <time datetime="2009-06-29T23:40:09+01:00">
                June 29th 2009 at 23:40</time>  
            </header>  
            <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit,
                sed do eiusmod tempor incididunt ut labore et dolore magna
                aliqua. Ut enim ad minim veniam, quis nostrud exercitation 
                ullamco laboris nisi ut.</p>  
        </article>  
    </section>     

app/views/pages/home.html.erb
<section>  
    <article class="blogPost">  
        <header>  
        <h2>Tässä ois vähä prototyyppiä</h2>  
        <p>Posted on <time datetime="2009-06-29T23:31:45+02:00">
            June 29th 2009</time> by <a href="#">tojuhaka</a> - 
            <a href="#comments">3 comments</a></p>  
        </header>  
        <p>I hope you enjoy our olives so much that you want to register
        yourself as an ultimate olive-member.
        <%= link_to "Sign up now!", signup_path%> here </p>
    </article>  

    <section id="comments">  
        <header>  
            <h3>Comments</h3>  
        </header>  
        <article>  
            <header>  
                <a href="#">George Washington</a> on 
                    <time datetime="2009-06-29T23:35:20+01:00">
                        June 29th 2009 at 23:35</time>  
            </header>  
            <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit, 
                sed do eiusmod tempor incididunt ut labore et dolore magna 
                aliqua. Ut enim ad minim veniam, quis nostrud exercitation 
                ullamco laboris nisi ut.</p>  
        </article>  
        <article>  
            <header>  
                <a href="#">Benjamin Franklin</a> on 
                <time datetime="2009-06-29T23:40:09+01:00">
                June 29th 2009 at 23:40</time>  
            </header>  
            <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit,
                sed do eiusmod tempor incididunt ut labore et dolore magna
                aliqua. Ut enim ad minim veniam, quis nostrud exercitation 
                ullamco laboris nisi ut.</p>  
        </article>  
    </section>     

    <section id="comment form">
        <form action="#" method="post">  
            <h3>Post a comment</h3>  
            <p>  
                <label for="name">Name</label>  
                <input name="name" id="name" type="text" required />  
            </p>  
            <p>  
                <label for="email">E-mail</label>  
                <input name="email" id="email" type="email" required />  
            </p>  
            <p>  
                <label for="website">Website</label>  
                <input name="website" id="website" type="url" />  
            </p>  
            <p>  
                <label for="comment">Comment</label>  
                <textarea name="comment" id="comment" required></textarea>  
            </p>  
            <p><input type="submit" value="Post comment" /></p>  
        </form>  
    </section>
</section>  

app/views/shared/_error_messages.html.erb
<% if object.errors.any? %>
  <div id="error_explanation">
    <h2><%= pluralize(object.errors.count, "error") %> 
        prohibited this <%= object.class.to_s.underscore.humanize.downcase %>
        from being saved:</h2>
    <p>There were problems with the following fields:</p>
    <ul>
    <% object.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
    </ul>
  </div>
<% end %>

app/views/users/edit.html.erb
<h1>Edit user</h1>
<%= form_for(@user) do |f| %>
  <%= render 'shared/error_messages', :object => f.object  %>
  <div class="field">
    <%= f.label :firstname , "Etunimi:"%>
    <%= f.text_field :firstname %>
  </div>
  <div class="field">
    <%= f.label :lastname , "Sukunimi:"%>
    <%= f.text_field :lastname %>
  </div>
  <div class="field">
    <%= f.label :nick , "Tunnus:"%>
    <%= f.text_field :nick %>
  </div>
  <div class="field">
    <%= f.label :email , "Sähköposti:"%>
    <%= f.text_field :email %>
  </div>
  <div class="field">
    <%= f.label :password , "Salasana:"%>
    <%= f.password_field :password %>
  </div>
  <div class="field">
    <%= f.label :password_confirmation, "Salasana uudelleen:" %>
    <%= f.password_field :password_confirmation %>
  </div>
  <div class="actions">
    <%= f.submit "Lähetä" %>
  </div>
<% end %>

<div>
  <%= gravatar_for @user %>
  <a href="http://gravatar.com/emails">change</a>
</div>

app/views/users/new.html.erb
<h1>Rekistöröityäksesi käyttäjäksi täytä seuraavat tiedot</h1>
<%= form_for(@user) do |f| %>
  <%= render 'shared/error_messages', :object => f.object %>
  <div class="field">
    <%= f.label :firstname , "Etunimi:"%>
    <%= f.text_field :firstname %>
  </div>
  <div class="field">
    <%= f.label :lastname , "Sukunimi:"%>
    <%= f.text_field :lastname %>
  </div>
  <div class="field">
    <%= f.label :nick , "Tunnus:"%>
    <%= f.text_field :nick %>
  </div>
  <div class="field">
    <%= f.label :email , "Sähköposti:"%>
    <%= f.text_field :email %>
  </div>
  <div class="field">
    <%= f.label :password , "Salasana:"%>
    <%= f.password_field :password %>
  </div>
  <div class="field">
    <%= f.label :password_confirmation, "Salasana uudelleen:" %>
    <%= f.password_field :password_confirmation %>
  </div>
  <div class="actions">
    <%= f.submit "Lähetä" %>
  </div>
<% end %>

app/views/users/show.html.erb
     <div class="profile"> 
      <h1>
        <%= gravatar_for @user %>
        <%= @user.nick %>
      </h1>
      <strong>Etunimi:</strong> <%= @user.firstname %><br />
      <strong>Sukunimi:</strong> <%= @user.lastname %><br />
      <strong>URL</strong>  <%= link_to user_url(@user), @user %>
      </div>